# Generated by Django 5.1 on 2024-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='which',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
