# Generated by Django 5.1 on 2024-10-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_meal_which'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='which',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Breakfast', max_length=20),
        ),
    ]
