# Generated by Django 5.1 on 2024-10-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_alter_meal_author_alter_meal_created_at_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
