# Generated by Django 5.1 on 2024-10-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_rename_quantitiy_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='title',
        ),
    ]
