# Generated by Django 5.1 on 2024-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_remove_meal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='protein',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sugar',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
